version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.0
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
